# Generated by Django 5.0.6 on 2024-06-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_exercise_image_exerciseset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='repetition_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='set_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
