# Generated by Django 5.0.6 on 2024-06-06 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_exercise_repetition_count_exercise_set_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
