# Generated by Django 5.0.6 on 2024-06-06 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_exerciseset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
